import type { Sport, StrengthExercise } from "@/types";
import type {
  ExerciseCategory,
  ExerciseDifficulty,
  ExerciseTrackingMode,
} from "@/types/training";

export type { ExerciseCategory, ExerciseDifficulty, ExerciseTrackingMode };

export interface ExerciseDef {
  id: string;
  name: string;
  sport: Sport;
  category: ExerciseCategory;
  strengthExercise?: StrengthExercise;
  primaryMuscles: string[];
  muscleGroups: string[];
  defaultSets: { reps: number; restSec: number }[];
  vbtTargetMs?: number;
  equipment?: string;
  difficulty?: ExerciseDifficulty;
  description?: string;
  hints?: string[];
  trackingMode?: ExerciseTrackingMode;
}

export const CATEGORY_LABELS: Record<ExerciseCategory, string> = {
  hypertrophy: "Гипертрофия",
  power: "Мощность",
  core: "Кор",
  agility: "Ловкость",
  "technique-drill": "Техника",
};

const HYPER_SETS = (reps: number, rest: number, sets = 3) =>
  Array.from({ length: sets }, () => ({ reps, restSec: rest }));

const DRILL_SETS = (rounds = 3, rest = 45) =>
  Array.from({ length: rounds }, () => ({ reps: 1, restSec: rest }));

export const EXERCISE_CATALOG: ExerciseDef[] = [
  // ── Сила / гипертрофия (камера) ─────────────────────────────────────────
  {
    id: "squat",
    name: "Присед",
    sport: "strength",
    category: "hypertrophy",
    strengthExercise: "squat",
    trackingMode: "pose",
    equipment: "штанга",
    difficulty: "intermediate",
    primaryMuscles: [
      "quadriceps_l",
      "quadriceps_r",
      "glutes_c",
      "hamstrings_l",
      "hamstrings_r",
    ],
    muscleGroups: ["Ноги", "Спина", "Кор"],
    defaultSets: HYPER_SETS(8, 90).concat([{ reps: 6, restSec: 120 }]),
    vbtTargetMs: 0.45,
    description: "Базовое упражнение для ног и корпуса.",
    hints: ["Колени по линии носков", "Глубина — параллель бедра полу"],
  },
  {
    id: "bench",
    name: "Жим лёжа",
    sport: "strength",
    category: "hypertrophy",
    strengthExercise: "bench",
    trackingMode: "pose",
    equipment: "штанга",
    difficulty: "intermediate",
    primaryMuscles: ["chest_l", "chest_r", "shoulders_l", "triceps_l", "triceps_r"],
    muscleGroups: ["Грудь", "Плечи"],
    defaultSets: HYPER_SETS(10, 75, 2).concat([{ reps: 8, restSec: 90 }]),
    vbtTargetMs: 0.35,
    description: "Жим для груди, плеч и трицепса.",
    hints: ["Лопатки сведены", "Локти ~45° к корпусу"],
  },
  {
    id: "lunge",
    name: "Выпады",
    sport: "strength",
    category: "hypertrophy",
    strengthExercise: "lunge",
    trackingMode: "pose",
    equipment: "гантели",
    difficulty: "beginner",
    primaryMuscles: [
      "quadriceps_l",
      "quadriceps_r",
      "glutes_l",
      "glutes_r",
      "hamstrings_l",
    ],
    muscleGroups: ["Ноги", "Кор"],
    defaultSets: HYPER_SETS(10, 60),
    vbtTargetMs: 0.4,
    description: "Односторонняя нагрузка на ноги и стабилизаторы.",
    hints: ["Корпус вертикально", "Колено не выходит за носок"],
  },
  // ── Сила / гипертрофия (guided) ─────────────────────────────────────────
  {
    id: "deadlift",
    name: "Становая тяга",
    sport: "strength",
    category: "hypertrophy",
    equipment: "штанга",
    difficulty: "advanced",
    primaryMuscles: ["back_c", "glutes_c", "hamstrings_l", "hamstrings_r"],
    muscleGroups: ["Спина", "Ноги"],
    defaultSets: HYPER_SETS(6, 120).concat([{ reps: 5, restSec: 150 }]),
    vbtTargetMs: 0.5,
    description: "Многосуставная тяга для задней цепи.",
    hints: ["Спина нейтральна", "Штанга близко к голеням"],
  },
  {
    id: "barbell_row",
    name: "Тяга штанги в наклоне",
    sport: "strength",
    category: "hypertrophy",
    equipment: "штанга",
    difficulty: "intermediate",
    primaryMuscles: ["back_c", "back_l", "back_r", "biceps_l", "biceps_r"],
    muscleGroups: ["Спина", "Плечи"],
    defaultSets: HYPER_SETS(10, 75),
    vbtTargetMs: 0.38,
    description: "Толщина и ширина спины.",
    hints: ["Тяните локтями к поясу", "Кор напряжён"],
  },
  {
    id: "overhead_press",
    name: "Жим стоя",
    sport: "strength",
    category: "hypertrophy",
    equipment: "штанга",
    difficulty: "intermediate",
    primaryMuscles: ["shoulders_l", "shoulders_r", "triceps_l", "triceps_r"],
    muscleGroups: ["Плечи", "Кор"],
    defaultSets: HYPER_SETS(8, 90),
    vbtTargetMs: 0.32,
    description: "Вертикальный жим для дельт.",
    hints: ["Кор и ягодицы напряжены", "Голова чуть вперёд при проходе"],
  },
  {
    id: "pull_up",
    name: "Подтягивания",
    sport: "strength",
    category: "hypertrophy",
    equipment: "турник",
    difficulty: "intermediate",
    primaryMuscles: ["back_c", "back_l", "back_r", "biceps_l", "biceps_r"],
    muscleGroups: ["Спина", "Плечи"],
    defaultSets: [
      { reps: 8, restSec: 90 },
      { reps: 6, restSec: 90 },
      { reps: 6, restSec: 120 },
    ],
    description: "Вертикальная тяга собственным весом.",
    hints: ["Грудь к перекладине", "Без рывков"],
  },
  {
    id: "lat_pulldown",
    name: "Тяга верхнего блока",
    sport: "strength",
    category: "hypertrophy",
    equipment: "блок",
    difficulty: "beginner",
    primaryMuscles: ["back_c", "back_l", "back_r"],
    muscleGroups: ["Спина"],
    defaultSets: HYPER_SETS(12, 60),
    description: "Альтернатива подтягиваниям для ширины спины.",
    hints: ["Локти вниз и назад", "Не отклоняйтесь сильно назад"],
  },
  {
    id: "hip_thrust",
    name: "Ягодичный мост",
    sport: "strength",
    category: "hypertrophy",
    equipment: "штанга",
    difficulty: "beginner",
    primaryMuscles: ["glutes_c", "glutes_l", "glutes_r", "hamstrings_l"],
    muscleGroups: ["Ноги"],
    defaultSets: HYPER_SETS(12, 75),
    description: "Изоляция ягодичных с акцентом на пиковое сокращение.",
    hints: ["Пауза вверху 1 сек", "Подбородок к груди"],
  },
  {
    id: "romanian_deadlift",
    name: "Румынская тяга",
    sport: "strength",
    category: "hypertrophy",
    equipment: "штанга",
    difficulty: "intermediate",
    primaryMuscles: ["hamstrings_l", "hamstrings_r", "glutes_c", "back_c"],
    muscleGroups: ["Ноги", "Спина"],
    defaultSets: HYPER_SETS(10, 75),
    vbtTargetMs: 0.42,
    description: "Задняя поверхность бедра и ягодицы.",
    hints: ["Таз назад", "Лёгкий изгиб в коленях"],
  },
  {
    id: "calf_raise",
    name: "Подъём на носки",
    sport: "strength",
    category: "hypertrophy",
    equipment: "тренажёр",
    difficulty: "beginner",
    primaryMuscles: ["calves_l", "calves_r"],
    muscleGroups: ["Ноги"],
    defaultSets: HYPER_SETS(15, 45, 4),
    description: "Икры — стабильность и отталкивание.",
    hints: ["Полная амплитуда", "Пауза внизу"],
  },
  {
    id: "lateral_raise",
    name: "Разведения в стороны",
    sport: "strength",
    category: "hypertrophy",
    equipment: "гантели",
    difficulty: "beginner",
    primaryMuscles: ["shoulders_l", "shoulders_r"],
    muscleGroups: ["Плечи"],
    defaultSets: HYPER_SETS(15, 45),
    description: "Средние дельты для ширины плеч.",
    hints: ["Локти чуть выше кистей", "Без инерции"],
  },
  {
    id: "triceps_extension",
    name: "Разгибания на трицепс",
    sport: "strength",
    category: "hypertrophy",
    equipment: "блок",
    difficulty: "beginner",
    primaryMuscles: ["triceps_l", "triceps_r"],
    muscleGroups: ["Плечи"],
    defaultSets: HYPER_SETS(12, 60),
    description: "Изоляция трицепса.",
    hints: ["Локти зафиксированы", "Полное разгибание"],
  },
  {
    id: "biceps_curl",
    name: "Сгибания на бицепс",
    sport: "strength",
    category: "hypertrophy",
    equipment: "гантели",
    difficulty: "beginner",
    primaryMuscles: ["biceps_l", "biceps_r"],
    muscleGroups: ["Плечи"],
    defaultSets: HYPER_SETS(12, 60),
    description: "Изоляция бицепса.",
    hints: ["Локти у корпуса", "Контроль негативной фазы"],
  },
  {
    id: "leg_press",
    name: "Жим ногами",
    sport: "strength",
    category: "hypertrophy",
    equipment: "тренажёр",
    difficulty: "beginner",
    primaryMuscles: ["quadriceps_l", "quadriceps_r", "glutes_c"],
    muscleGroups: ["Ноги"],
    defaultSets: HYPER_SETS(12, 90),
    vbtTargetMs: 0.48,
    description: "Объёмная нагрузка на квадрицепс без осевой нагрузки на спину.",
    hints: ["Не отрывайте таз", "Колени по линии носков"],
  },
  {
    id: "face_pull",
    name: "Фейс-пул",
    sport: "strength",
    category: "hypertrophy",
    equipment: "блок",
    difficulty: "beginner",
    primaryMuscles: ["shoulders_l", "shoulders_r", "back_c"],
    muscleGroups: ["Плечи", "Спина"],
    defaultSets: HYPER_SETS(15, 45),
    description: "Задние дельты и здоровье плечевого пояса.",
    hints: ["Локти высоко", "Сведите лопатки"],
  },
  {
    id: "chest_fly",
    name: "Разведения на грудь",
    sport: "strength",
    category: "hypertrophy",
    equipment: "гантели",
    difficulty: "beginner",
    primaryMuscles: ["chest_l", "chest_r"],
    muscleGroups: ["Грудь"],
    defaultSets: HYPER_SETS(12, 60),
    description: "Растяжение и сокращение грудных.",
    hints: ["Лёгкий изгиб в локтях", "Контроль амплитуды"],
  },
  {
    id: "leg_curl",
    name: "Сгибания ног",
    sport: "strength",
    category: "hypertrophy",
    equipment: "тренажёр",
    difficulty: "beginner",
    primaryMuscles: ["hamstrings_l", "hamstrings_r"],
    muscleGroups: ["Ноги"],
    defaultSets: HYPER_SETS(12, 60),
    description: "Изоляция бицепса бедра.",
    hints: ["Таз прижат", "Медленное опускание"],
  },
  {
    id: "hip_abduction",
    name: "Отведение бедра",
    sport: "strength",
    category: "hypertrophy",
    equipment: "тренажёр",
    difficulty: "beginner",
    primaryMuscles: ["glutes_l", "glutes_r"],
    muscleGroups: ["Ноги"],
    defaultSets: HYPER_SETS(15, 45),
    description: "Средняя ягодичная и стабилизация таза.",
    hints: ["Корпус неподвижен", "Пауза в пике"],
  },
  {
    id: "seated_row",
    name: "Тяга сидя",
    sport: "strength",
    category: "hypertrophy",
    equipment: "блок",
    difficulty: "beginner",
    primaryMuscles: ["back_c", "back_l", "back_r"],
    muscleGroups: ["Спина"],
    defaultSets: HYPER_SETS(12, 75),
    description: "Горизонтальная тяга для толщины спины.",
    hints: ["Грудь к рукоятке", "Лопатки в конце"],
  },
  {
    id: "plank_core",
    name: "Планка / кор",
    sport: "strength",
    category: "core",
    equipment: "коврик",
    difficulty: "beginner",
    primaryMuscles: ["abs_c", "abs_l", "abs_r", "back_c"],
    muscleGroups: ["Кор", "Спина"],
    defaultSets: DRILL_SETS(2, 45),
    description: "Статическое укрепление кора.",
    hints: ["Таз нейтрален", "Дышите ровно"],
  },
  // ── Бокс S&C ────────────────────────────────────────────────────────────
  {
    id: "boxing_drill",
    name: "Бокс · комбо",
    sport: "boxing",
    category: "technique-drill",
    trackingMode: "guided",
    equipment: "перчатки",
    difficulty: "intermediate",
    primaryMuscles: [
      "shoulders_l",
      "shoulders_r",
      "triceps_l",
      "triceps_r",
      "abs_c",
    ],
    muscleGroups: ["Плечи", "Кор"],
    defaultSets: DRILL_SETS(3, 45),
    description: "Комбинации ударов по таймеру.",
    hints: ["Руки к подбородку", "Вес на передней ноге"],
  },
  {
    id: "shadow_boxing",
    name: "Тень · раунды",
    sport: "boxing",
    category: "technique-drill",
    trackingMode: "guided",
    equipment: "перчатки",
    difficulty: "beginner",
    primaryMuscles: ["shoulders_l", "shoulders_r", "abs_c"],
    muscleGroups: ["Плечи", "Кор"],
    defaultSets: DRILL_SETS(3, 60),
    description: "Техника и кардио без снаряда.",
    hints: ["Движение головы", "Ритм дыхания"],
  },
  {
    id: "heavy_bag_intervals",
    name: "Мешок · интервалы",
    sport: "boxing",
    category: "power",
    trackingMode: "guided",
    equipment: "боксёрский мешок",
    difficulty: "intermediate",
    primaryMuscles: ["shoulders_l", "shoulders_r", "triceps_l", "abs_c"],
    muscleGroups: ["Плечи", "Кор"],
    defaultSets: DRILL_SETS(4, 60),
    description: "Мощные серии на мешок 2:1 работа/отдых.",
    hints: ["Взрыв в начале серии", "Возврат рук в стойку"],
  },
  {
    id: "medicine_ball_slam",
    name: "Слэмы медболом",
    sport: "boxing",
    category: "power",
    trackingMode: "guided",
    equipment: "медбол",
    difficulty: "intermediate",
    primaryMuscles: ["abs_c", "shoulders_l", "shoulders_r", "back_c"],
    muscleGroups: ["Кор", "Плечи"],
    defaultSets: HYPER_SETS(10, 45),
    description: "Взрывная работа корпуса.",
    hints: ["Тяните мяч вверх", "Бейте в пол всем корпусом"],
  },
  {
    id: "battle_ropes",
    name: "Канаты",
    sport: "boxing",
    category: "power",
    trackingMode: "guided",
    equipment: "канаты",
    difficulty: "intermediate",
    primaryMuscles: ["shoulders_l", "shoulders_r", "abs_c"],
    muscleGroups: ["Плечи", "Кор"],
    defaultSets: DRILL_SETS(4, 40),
    description: "Интервалы на канатах для выносливости плеч.",
    hints: ["Кор напряжён", "Ровный темп"],
  },
  {
    id: "jump_rope",
    name: "Скакалка",
    sport: "boxing",
    category: "agility",
    trackingMode: "guided",
    equipment: "скакалка",
    difficulty: "beginner",
    primaryMuscles: ["calves_l", "calves_r", "quadriceps_l"],
    muscleGroups: ["Ноги"],
    defaultSets: DRILL_SETS(3, 30),
    description: "Координация ног и кардио.",
    hints: ["Прыжки низкие", "Запястья крутят верёвку"],
  },
  {
    id: "plyo_pushup",
    name: "Плио отжимания",
    sport: "boxing",
    category: "power",
    trackingMode: "guided",
    equipment: "коврик",
    difficulty: "advanced",
    primaryMuscles: ["chest_l", "chest_r", "triceps_l", "triceps_r"],
    muscleGroups: ["Грудь", "Плечи"],
    defaultSets: [
      { reps: 8, restSec: 60 },
      { reps: 6, restSec: 75 },
      { reps: 6, restSec: 90 },
    ],
    description: "Взрывной жим для мощности удара.",
    hints: ["Мягкое приземление", "Кор жёсткий"],
  },
  {
    id: "rotational_core_boxing",
    name: "Ротация корпуса",
    sport: "boxing",
    category: "core",
    trackingMode: "guided",
    equipment: "медбол",
    difficulty: "intermediate",
    primaryMuscles: ["abs_c", "abs_l", "abs_r", "back_c"],
    muscleGroups: ["Кор"],
    defaultSets: HYPER_SETS(12, 45, 3),
    description: "Вращательная сила для хуков и кроссов.",
    hints: ["Бёдра ведут движение", "Взгляд за мячом"],
  },
  {
    id: "landmine_press",
    name: "Жим лэндмайн",
    sport: "boxing",
    category: "power",
    trackingMode: "guided",
    equipment: "штанга",
    difficulty: "intermediate",
    primaryMuscles: ["shoulders_l", "shoulders_r", "chest_l", "abs_c"],
    muscleGroups: ["Плечи", "Кор"],
    defaultSets: HYPER_SETS(8, 75),
    description: "Угловой жим для силы удара.",
    hints: ["Шаг вперёд при жиме", "Кор стабилен"],
  },
  {
    id: "sled_push",
    name: "Толкание саней",
    sport: "boxing",
    category: "power",
    trackingMode: "guided",
    equipment: "сани",
    difficulty: "intermediate",
    primaryMuscles: ["quadriceps_l", "quadriceps_r", "glutes_c", "calves_l"],
    muscleGroups: ["Ноги"],
    defaultSets: DRILL_SETS(4, 90),
    description: "Низкоинтенсивная мощность ног.",
    hints: ["Корпус наклонён", "Короткие мощные шаги"],
  },
  {
    id: "footwork_ladder",
    name: "Лестница · ноги",
    sport: "boxing",
    category: "agility",
    trackingMode: "guided",
    equipment: "лестница",
    difficulty: "beginner",
    primaryMuscles: ["calves_l", "calves_r", "quadriceps_l"],
    muscleGroups: ["Ноги"],
    defaultSets: DRILL_SETS(4, 30),
    description: "Быстрые перестановки для ринга.",
    hints: ["На носках", "Руки в стойке"],
  },
  // ── Теннис S&C ──────────────────────────────────────────────────────────
  {
    id: "tennis_drill",
    name: "Теннис · удары",
    sport: "tennis",
    category: "technique-drill",
    trackingMode: "guided",
    equipment: "ракетка",
    difficulty: "intermediate",
    primaryMuscles: [
      "shoulders_l",
      "shoulders_r",
      "forearms_l",
      "forearms_r",
      "back_c",
    ],
    muscleGroups: ["Плечи", "Спина"],
    defaultSets: DRILL_SETS(3, 40),
    description: "Имитация ударов по таймеру.",
    hints: ["Разворот корпуса", "Удар перед корпусом"],
  },
  {
    id: "split_step_drill",
    name: "Сплит-степ",
    sport: "tennis",
    category: "agility",
    trackingMode: "guided",
    equipment: "корт",
    difficulty: "beginner",
    primaryMuscles: ["calves_l", "calves_r", "quadriceps_l", "quadriceps_r"],
    muscleGroups: ["Ноги"],
    defaultSets: DRILL_SETS(4, 35),
    description: "Реакция на подачу соперника.",
    hints: ["Мягкое приземление", "Колени согнуты"],
  },
  {
    id: "lateral_cone_hops",
    name: "Прыжки между конусами",
    sport: "tennis",
    category: "agility",
    trackingMode: "guided",
    equipment: "конусы",
    difficulty: "intermediate",
    primaryMuscles: ["quadriceps_l", "quadriceps_r", "glutes_l", "glutes_r"],
    muscleGroups: ["Ноги"],
    defaultSets: DRILL_SETS(4, 40),
    description: "Боковая скорость для кортовых перемещений.",
    hints: ["Кор низко", "Взгляд вперёд"],
  },
  {
    id: "rotator_cuff",
    name: "Вращатели плеча",
    sport: "tennis",
    category: "hypertrophy",
    trackingMode: "guided",
    equipment: "резинка",
    difficulty: "beginner",
    primaryMuscles: ["shoulders_l", "shoulders_r"],
    muscleGroups: ["Плечи"],
    defaultSets: HYPER_SETS(15, 45),
    description: "Профилактика плечевых травм.",
    hints: ["Лёгкий вес", "Медленный контроль"],
  },
  {
    id: "med_ball_rotational_throw",
    name: "Медбол · ротация",
    sport: "tennis",
    category: "power",
    trackingMode: "guided",
    equipment: "медбол",
    difficulty: "intermediate",
    primaryMuscles: ["abs_c", "back_c", "shoulders_l", "shoulders_r"],
    muscleGroups: ["Кор", "Плечи"],
    defaultSets: HYPER_SETS(10, 50, 3),
    description: "Взрывная ротация как при ударе.",
    hints: ["Задняя нога ведёт", "Бросок от бедра"],
  },
  {
    id: "single_leg_rdl",
    name: "RDL на одной ноге",
    sport: "tennis",
    category: "hypertrophy",
    trackingMode: "guided",
    equipment: "гантель",
    difficulty: "intermediate",
    primaryMuscles: ["hamstrings_l", "hamstrings_r", "glutes_l", "glutes_r"],
    muscleGroups: ["Ноги", "Кор"],
    defaultSets: HYPER_SETS(10, 60, 3),
    description: "Баланс и задняя цепь для кортовых рывков.",
    hints: ["Таз ровный", "Опора на всю стопу"],
  },
  {
    id: "lateral_lunge_tennis",
    name: "Боковые выпады",
    sport: "tennis",
    category: "hypertrophy",
    trackingMode: "guided",
    equipment: "гантели",
    difficulty: "beginner",
    primaryMuscles: ["quadriceps_l", "quadriceps_r", "glutes_l", "glutes_r"],
    muscleGroups: ["Ноги"],
    defaultSets: HYPER_SETS(10, 60, 3),
    description: "Сила в боковых смещениях по корту.",
    hints: ["Колено по линии носка", "Корпус вертикально"],
  },
  {
    id: "serve_motion_drill",
    name: "Имитация подачи",
    sport: "tennis",
    category: "technique-drill",
    trackingMode: "guided",
    equipment: "ракетка",
    difficulty: "intermediate",
    primaryMuscles: ["shoulders_l", "shoulders_r", "back_c", "abs_c"],
    muscleGroups: ["Плечи", "Кор"],
    defaultSets: DRILL_SETS(4, 50),
    description: "Кинематическая цепочка подачи без мяча.",
    hints: ["Трофейная поза", "Взрыв вверх"],
  },
  {
    id: "agility_ladder",
    name: "Лестница · теннис",
    sport: "tennis",
    category: "agility",
    trackingMode: "guided",
    equipment: "лестница",
    difficulty: "beginner",
    primaryMuscles: ["calves_l", "calves_r", "quadriceps_l"],
    muscleGroups: ["Ноги"],
    defaultSets: DRILL_SETS(4, 30),
    description: "Быстрые ноги для выхода на мяч.",
    hints: ["Короткие шаги", "Руки в игровой позиции"],
  },
  {
    id: "tennis_footwork",
    name: "Кортовая работа ног",
    sport: "tennis",
    category: "agility",
    trackingMode: "guided",
    equipment: "корт",
    difficulty: "intermediate",
    primaryMuscles: ["quadriceps_l", "quadriceps_r", "calves_l", "calves_r"],
    muscleGroups: ["Ноги"],
    defaultSets: DRILL_SETS(3, 45),
    description: "V-образные и T-образные перемещения.",
    hints: ["Первый шаг взрывной", "Возврат в центр"],
  },
];

export function exerciseById(id: string): ExerciseDef | undefined {
  return EXERCISE_CATALOG.find((e) => e.id === id);
}

export function exercisesForMuscleGroup(group: string): ExerciseDef[] {
  return EXERCISE_CATALOG.filter((e) => e.muscleGroups.includes(group));
}

export function exercisesBySport(sport: Sport): ExerciseDef[] {
  return EXERCISE_CATALOG.filter((e) => e.sport === sport);
}

export function exercisesByCategory(
  category: ExerciseCategory
): ExerciseDef[] {
  return EXERCISE_CATALOG.filter((e) => e.category === category);
}

export function catalogStats(): Record<ExerciseCategory, number> {
  const stats: Record<ExerciseCategory, number> = {
    hypertrophy: 0,
    power: 0,
    core: 0,
    agility: 0,
    "technique-drill": 0,
  };
  for (const ex of EXERCISE_CATALOG) {
    stats[ex.category]++;
  }
  return stats;
}
